// /features/auth/fuelSlice.js
import { createSlice } from "@reduxjs/toolkit";

// Assume you have thunks for login and logout (similar to the previous example)

const electricitySlice = createSlice({
  name: "electricity",
  initialState: {
    electricityRecords: [
      {
        id: 1,
        bill_date: "2024-01-01",
        bill_start: "2024-01-01",
        bill_end: "2024-01-05",
        site: "site-3",
        source_type: "Renewable",
        electricity_resource: "wind",
        transaction_type: "Purchased",
        electricity_board: "MSDCL",
        unit_used: "500",
        unit: "kWh",
        amount_paid: 357896,
        emission_factor: 0.25,
        currency: "INR",
        evidence: "",
        status: "Uploaded",
        feedback: "OK",
        submitted_by: "",
        approved_by: "",
        total_co2e_kg: "4180.47195",
        co2e_co2_kg: "4180.3788",
        co2e_ch4_kg: "0.05175",
        co2e_n2o_kg: "0.0414",
        usage_required_unit: "8",
        usage_factor: "13.64",
        usage_unit_type: "4",
        usage_in_kwh: "313.72",
        quarter: "4",
        year: "2016",
        site_id: 3,
        electricity_resource_id: 3,
        electricity_board_id: 2,
        unit_id: 1,
        currency_id: 1,
      },
      {
        id: 2,
        bill_date: "2024-02-05",
        bill_start: "2024-02-01",
        bill_end: "2024-02-10",
        site: 'site-3',
        source_type: "Non-Renewable",
        electricity_resource: "coal",
        transaction_type: "Consumed",
        electricity_board: "Electra",
        unit_used: "700",
        unit: "kWh",
        amount_paid: 457896,
        emission_factor: 0.35,
        currency: "USD",
        evidence: "",
        status: "Pending",
        feedback: "",
        submitted_by: "John Doe",
        approved_by: "Jane Smith",
        total_co2e_kg: "3200.125",
        co2e_co2_kg: "3200.032",
        co2e_ch4_kg: "0.04125",
        co2e_n2o_kg: "0.0369",
        usage_required_unit: "9",
        usage_factor: "12.75",
        usage_unit_type: "3",
        usage_in_kwh: "280.50",
        quarter: "2",
        year: "2024",
        site_id: 3,
        electricity_resource_id: 10,
        electricity_board_id: 1,
        unit_id: 1,
        currency_id: 2,
      },
      {
        id: 3,
        bill_date: "2024-03-12",
        bill_start: "2024-03-10",
        bill_end: "2024-03-15",
        site: 'site-3',
        source_type: "Renewable",
        electricity_resource: "solar",
        transaction_type: "Purchased",
        electricity_board: "XYZ Electric",
        unit_used: "600",
        unit: "kWh",
        amount_paid: 257896,
        emission_factor: 0.45,
        currency: "INR",
        evidence: "",
        status: "Approved",
        feedback: "Excellent service!",
        submitted_by: "Alice Johnson",
        approved_by: "Bob Brown",
        total_co2e_kg: "2100.336",
        co2e_co2_kg: "2100.235",
        co2e_ch4_kg: "0.03275",
        co2e_n2o_kg: "0.02835",
        usage_required_unit: "7",
        usage_factor: "15.25",
        usage_unit_type: "2",
        usage_in_kwh: "510.50",
        quarter: "1",
        year: "2024",
        site_id: 3,
        electricity_resource_id: 2,
        electricity_board_id: 5,
        unit_id: 1,
        currency_id: 1,
      },
      {
        id: 4,
        bill_date: "2024-04-20",
        bill_start: "2024-04-15",
        bill_end: "2024-04-25",
        site: 'site-3',
        source_type: "Renewable",
        electricity_resource: "hydro",
        transaction_type: "Purchased",
        electricity_board: "Hydro Power Inc.",
        unit_used: "800",
        unit: "kWh",
        amount_paid: 357896,
        emission_factor: 0.15,
        currency: "INR",
        evidence: "",
        status: "Uploaded",
        feedback: "Good",
        submitted_by: "Michael Smith",
        approved_by: "David Johnson",
        total_co2e_kg: "1500.891",
        co2e_co2_kg: "1500.780",
        co2e_ch4_kg: "0.02875",
        co2e_n2o_kg: "0.02135",
        usage_required_unit: "10",
        usage_factor: "12.50",
        usage_unit_type: "5",
        usage_in_kwh: "650.25",
        quarter: "2",
        year: "2023",
        site_id: 3,
        electricity_resource_id: 1,
        electricity_board_id: 6,
        unit_id: 1,
        currency_id: 1,
      },
      {
        id: 5,
        bill_date: "2024-05-05",
        bill_start: "2024-05-01",
        bill_end: "2024-05-10",
        site: "site-3",
        source_type: "Non-Renewable",
        electricity_resource: "Diesel",
        transaction_type: "Consumed",
        electricity_board: "Andhra Pradesh Power",
        unit_used: "900",
        unit: "kWh",
        amount_paid: 657896,
        emission_factor: 0.55,
        currency: "INR",
        evidence: "",
        status: "Pending",
        feedback: "",
        submitted_by: "Emma Wilson",
        approved_by: "",
        total_co2e_kg: "4000.225",
        co2e_co2_kg: "4000.123",
        co2e_ch4_kg: "0.06535",
        co2e_n2o_kg: "0.0589",
        usage_required_unit: "12",
        usage_factor: "11.75",
        usage_unit_type: "6",
        usage_in_kwh: "780.90",
        quarter: "3",
        year: "2023",
        site_id: 3,
        electricity_resource_id: 7,
        electricity_board_id: 4,
        unit_id: 1,
        currency_id: 1,
      },
      {
        id: 6,
        bill_date: "2024-06-15",
        bill_start: "2024-06-10",
        bill_end: "2024-06-20",
        site: 'site-2',
        source_type: "Renewable",
        electricity_resource: "geothermal",
        transaction_type: "Purchased",
        electricity_board: "MSDCL",
        unit_used: "1000",
        unit: "kWh",
        amount_paid: 857896,
        emission_factor: 0.18,
        currency: "USD",
        evidence: "",
        status: "Approved",
        feedback: "Satisfactory",
        submitted_by: "Sophia Martinez",
        approved_by: "William Taylor",
        total_co2e_kg: "2800.789",
        co2e_co2_kg: "2800.680",
        co2e_ch4_kg: "0.0456",
        co2e_n2o_kg: "0.03965",
        usage_required_unit: "15",
        usage_factor: "16.50",
        usage_unit_type: "1",
        usage_in_kwh: "620.75",
        quarter: "4",
        year: "2022",
        site_id: 2,
        electricity_resource_id: 4,
        electricity_board_id: 2,
        unit_id: 1,
        currency_id: 2,
      },
    ],
    electricityForm: {},

    filters: null,
    sorting: null,
    transaction_type: [
      { id: 1, name: "Purchased" },
      { id: 2, name: "Consumed" },
    ],
    electricityRecordType: 1,
    itemsPerPage: 10,
    totalPages: 1,
    currentPage: 1,
    totalCount: 10,
    siteData: [
      { id: 1, site: "site-1" },
      { id: 2, site: "site-2" },
      { id: 3, site: "site-3" },
      { id: 4, site: "site-4" },
    ],
    electricityTypeData: [],
    electricityResourcesData: [
      { id: 1, electricity_resource: "Hydro" },
      { id: 2, electricity_resource: "Solar" },
      { id: 3, electricity_resource: "Wind" },
      { id: 4, electricity_resource: "Geothermal" },
      { id: 5, electricity_resource: "Nuclear" },
      { id: 6, electricity_resource: "Gas" },
      { id: 7, electricity_resource: "Diesel" },
      { id: 8, electricity_resource: "Mixed Renewable" },
      { id: 9, electricity_resource: "tidal" },
      { id: 10, electricity_resource: "coal" },
    ],
    sourceTypeData: [],
    useTypeData: [],
    electricity_boardData: [
      { id: 1, electricity_board: "Electra" },
      { id: 2, electricity_board: "MSDCL" },
      { id: 3, electricity_board: "Telangana Power" },
      { id: 4, electricity_board: "Andhra Pradesh Power" },
      { id: 5, electricity_board: "XYZ Electric" },
      { id: 6, electricity_board: "Hydro Power Inc." },
    ],
    unitData: [
      { id: 1, unit: "kWh" },
      { id: 2, unit: "Joules" },
      { id: 3, unit: "Gigajoules" },
      { id: 4, unit: "kilojoules" },
    ],
    currencyData: [
      { id: 1, currency: "INR" },
      { id: 2, currency: "USD" },
    ],
  },
  reducers: {
    setElectricityRecords: (state, action) => {
      state.electricityRecords = action.payload.data;
    },
    setElectricityForm: (state, action) => {
      return {
        ...state,
        electricityForm: {
          ...state.electricityForm,
          ...action.payload,
        },
      };
    },
    resetElectricityForm: (state, action) => {
      state.electricityForm = {};
    },
    setFilters: (state, action) => {
      state.filters = action.payload;
    },
    setSorting: (state, action) => {
      state.sorting = action.payload;
    },
    setFuelRecordType: (state, action) => {
      state.fuelRecordType = action.payload;
    },
    setItemsPerPage: (state, action) => {
      state.itemsPerPage = action.payload;
    },
    setCurrentPage: (state, action) => {
      state.currentPage = action.payload;
    },
    setTotalPages: (state, action) => {
      state.totalPages = action.payload;
    },
    setTotalCount: (state, action) => {
      state.totalCount = action.payload;
    },
    setSiteData: (state, action) => {
      state.siteData = action.payload;
    },
    setFuelTypeData: (state, action) => {
      state.electricityTypeData = action.payload;
    },
    setSourceTypeData: (state, action) => {
      state.sourceTypeData = action.payload;
    },
    setUseTypeData: (state, action) => {
      state.useTypeData = action.payload;
    },
    setUnitData: (state, action) => {
      state.unitData = action.payload;
    },
    setCurrencyData: (state, action) => {
      state.currencyData = action.payload;
    },
    addElectricityData: (state, action) => {
      // const newRecords = [...state.electricityRecords];
      // newRecords.push(action.payload);
      // state.electricityRecords = newRecords;
    },
  },
});

export const {
  addElectricityData,
  setFilters,
  setElectricityForm,
  setElectricityRecordType,
  setElectricityRecords,
  setSorting,
  setCurrentPage,
  setItemsPerPage,
  setTotalCount,
  setTotalPages,
  setCurrencyData,
  setElectricityTypeData,
  setSiteData,
  setSourceTypeData,
  setUnitData,
  setUseTypeData,
  resetElectricityForm
} = electricitySlice.actions;
export default electricitySlice.reducer;
